# Camera K-fold CV + ensemble — Bangkok CCTV Vehicle Detection (2110531 DSDE midterm)

Runs on a **Kaggle Notebook (GPU T4)** with the competition data attached, or on Colab.

* **Validation:** `StratifiedGroupKFold` with *camera* as the group → 5 folds × 3 held-out cameras. Every camera is used for
  validation exactly once (honest out-of-fold score for unseen cameras) and for training in the other 4 folds.
* **Model:** YOLO26m (COCO-pretrained), imgsz 960, same cleaning / repeat-factor sampling as `vehicle_detection.ipynb`.
* **Final prediction:** the 5 fold models (each with TTA) are fused with **Weighted Boxes Fusion**.
* **Folds** are fixed to the camera assignment of the submitted run (`FIXED_FOLDS`), because `StratifiedGroupKFold`
  gives a different assignment on other scikit-learn versions.
* **Reproduce without training:** put the submitted weights at `cv_out/fold{k}/best.pt`; those folds are only predicted.
* **Time guard:** a fold is only started if it can finish before the session limit, so the outputs are always saved.
  Folds that did not fit are run in a later session (set `FOLDS` below) and all fold outputs are combined at the end.

In [1]:
# Offline install (Kaggle notebooks without internet): wheels + weights come from the private dataset
# 'dsde-midterm-offline-pkgs'. With internet (Colab), the normal pip install is used instead.
import glob, os, shutil, subprocess, sys, traceback
def _log_exc(shell, etype, evalue, tb, tb_offset=None):      # keep a copy of any error in the outputs (progress.log)
    with open('progress.log', 'a') as fh:
        fh.write(''.join(traceback.format_exception(etype, evalue, tb)))
    shell.showtraceback((etype, evalue, tb), tb_offset=tb_offset)
get_ipython().set_custom_exc((BaseException,), _log_exc)
def plog(msg):
    with open('progress.log', 'a') as fh:
        print(msg, file=fh)
whl = glob.glob('/kaggle/input/**/ultralytics-8.4.163-py3-none-any.whl', recursive=True)
if whl:
    PKG_DIR = os.path.dirname(whl[0])
    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', '--no-index', '--no-deps'] + glob.glob(f'{PKG_DIR}/*.whl'), check=True)
    for f in ['yolo26m.pt', 'yolo26n.pt']:            # yolo26n.pt is used by the AMP check
        shutil.copy(f'{PKG_DIR}/{f}', f)
else:
    PKG_DIR = None
    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'ultralytics==8.4.163', 'ensemble-boxes', 'pycocotools', 'scikit-learn'], check=True)
print('packages from', PKG_DIR or 'PyPI'); plog('install ok')

packages from PyPI

In [2]:
import os, re, json, glob, shutil, time, math, random, contextlib, io
from pathlib import Path
import numpy as np, pandas as pd, torch, ultralytics
from PIL import Image
from ultralytics import YOLO
from sklearn.model_selection import StratifiedGroupKFold
T_START = time.time()
from ultralytics.utils import USER_CONFIG_DIR
if PKG_DIR and not (USER_CONFIG_DIR / 'Arial.ttf').exists():
    shutil.copy(f'{PKG_DIR}/Arial.ttf', USER_CONFIG_DIR / 'Arial.ttf')   # font for plots (no download offline)
N_GPU = torch.cuda.device_count()
print('ultralytics', ultralytics.__version__, '| torch', torch.__version__, '| GPUs:',
      [torch.cuda.get_device_name(i) for i in range(N_GPU)])
if os.path.exists('/kaggle/input') and N_GPU == 0 and os.environ.get('SMOKE_TEST') != '1':
    raise RuntimeError('No GPU in this Kaggle session: enable "GPU T4" (needs a phone-verified Kaggle account)')

ultralytics 8.4.163 | torch 2.8.0+cu126 | GPUs: ['NVIDIA GeForce RTX 3050 Ti Laptop GPU']

## Config

In [3]:
FOLDS        = [0,1,2,3,4]        # folds to train in THIS session (0..4)
N_FOLDS      = 5
MODEL        = 'yolo26m.pt'
IMGSZ        = 960
EPOCHS       = 30
PATIENCE     = 10
BATCH_PER_GPU = 8
SEED         = 42
TTA          = True
CONF         = 0.001
MAX_DET      = 300              # raw per model; pycocotools later keeps top-100 per image & class
BUDGET_H     = 11.0             # Kaggle GPU session limit is 12 h -> keep a safety margin
CLASSES = ['Car', 'Motorcycle', 'Bus', 'Truck', 'Tuktuk', 'Van', 'Pickup', 'Songthaew']
W, H = 352, 288
if os.environ.get('SMOKE_TEST') == '1':          # quick local pipeline check
    MODEL, IMGSZ, EPOCHS, FOLDS, BATCH_PER_GPU = 'yolo26n.pt', 320, 1, [0], 8

KAGGLE = os.path.exists('/kaggle/input')
if KAGGLE:
    found = []
    for root, dirs, files in os.walk('/kaggle/input', followlinks=True):
        if root.count(os.sep) <= 6:
            plog(f'{root}: {sorted(dirs)[:10]} {[f for f in files if not f.endswith(".jpg")][:10]}')
        if 'train.csv' in files:
            found.append(root)
    if not found:                 # data attached as a private dataset that still contains the competition zip
        import zipfile
        zips = [z for z in glob.glob('/kaggle/input/**/*.zip', recursive=True)]
        plog(f'extracting {zips}')
        for z in zips:
            zipfile.ZipFile(z).extractall('/tmp/data')
        found = [r for r, d, f in os.walk('/tmp/data') if 'train.csv' in f]
    RAW = Path(sorted(found)[0])
    WORK = Path('/kaggle/working')
else:                           # Colab / local: expects data in ./data/raw (kaggle competitions download ...)
    RAW = Path('data/raw'); WORK = Path('.')
OUT = WORK / 'cv_out'; OUT.mkdir(parents=True, exist_ok=True)
TMP = Path('/tmp/dsde'); TMP.mkdir(parents=True, exist_ok=True)
TRAIN_IMG_DIR = next(p for p in [RAW / 'train' / 'train', RAW / 'train'] if p.is_dir() and any(p.glob('*.jpg')))
TEST_IMG_DIR = next(p for p in [RAW / 'test' / 'test', RAW / 'test'] if p.is_dir() and any(p.glob('*.jpg')))
print(RAW, TRAIN_IMG_DIR, TEST_IMG_DIR, OUT); plog(f'paths {RAW} {TRAIN_IMG_DIR}')
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)

data\raw data\raw\train\train data\raw\test\test cv_out

## Data, cleaning and camera folds (same rules as the main notebook)

In [4]:
train_df = pd.read_csv(RAW / 'train.csv')
train_files = sorted(p.name for p in TRAIN_IMG_DIR.glob('*.jpg'))
test_files = sorted(p.name for p in TEST_IMG_DIR.glob('*.jpg'))
cam_of = lambda f: f.split('_')[0]

def box_iou(a, b):
    lt = np.maximum(a[:, None, :2], b[None, :, :2]); rb = np.minimum(a[:, None, 2:], b[None, :, 2:])
    inter = np.clip(rb - lt, 0, None).prod(-1)
    area = lambda x: (x[:, 2] - x[:, 0]) * (x[:, 3] - x[:, 1])
    return inter / (area(a)[:, None] + area(b)[None] - inter + 1e-9)

clean = train_df[train_df.image_id.isin(train_files)].copy()
for c, lim in [('x1', W), ('x2', W), ('y1', H), ('y2', H)]:
    clean[c] = clean[c].clip(0, lim)
clean = clean[~clean.duplicated(['image_id', 'class_id', 'x1', 'y1', 'x2', 'y2'])]
clean = clean[((clean.x2 - clean.x1) >= 2) & ((clean.y2 - clean.y1) >= 2)]
drop = []
for f, g in clean.groupby('image_id'):
    if len(g) > 1:
        iou = np.triu(box_iou(g[['x1', 'y1', 'x2', 'y2']].values, g[['x1', 'y1', 'x2', 'y2']].values), 1)
        drop += [g.index[j] for i, j in zip(*np.where(iou > 0.9)) if g.class_id.iloc[i] == g.class_id.iloc[j]]
clean = clean.drop(index=list(set(drop)))
print('boxes raw', len(train_df), '-> clean', len(clean))

# StratifiedGroupKFold: group = camera, stratify on the rarest class present in each image
freq = clean.class_id.value_counts()
rarest = {f: g.class_id.iloc[g.class_id.map(freq).values.argmin()] for f, g in clean.groupby('image_id')}
y = np.array([rarest.get(f, 8) for f in train_files]); groups = np.array([cam_of(f) for f in train_files])
fold_of_cam = {}
for k, (_, va) in enumerate(StratifiedGroupKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED).split(train_files, y, groups)):
    for c in set(groups[va]):
        fold_of_cam[c] = k
# The assignment above depends on the scikit-learn version. For exact reproducibility the folds of the submitted run
# (Kaggle, scikit-learn of the Kaggle image) are fixed here; set USE_FIXED_FOLDS = False to recompute them.
USE_FIXED_FOLDS = True
FIXED_FOLDS = {0: ['1426', '1427', '172'], 1: ['1066', '182', '222'], 2: ['229', '232', '244'],
               3: ['1407', '1437', '180'], 4: ['12', '214', '231']}
if USE_FIXED_FOLDS:
    fold_of_cam = {c: k for k, cams in FIXED_FOLDS.items() for c in cams}
json.dump({k: sorted(c for c, v in fold_of_cam.items() if v == k) for k in range(N_FOLDS)}, open(OUT / 'folds.json', 'w'), indent=1)
cc = pd.crosstab(clean.image_id.map(cam_of).map(fold_of_cam), clean.class_id).reindex(columns=range(8), fill_value=0)
cc.columns = CLASSES; cc.index.name = 'val fold'
print({k: sorted(c for c, v in fold_of_cam.items() if v == k) for k in range(N_FOLDS)})
cc

boxes raw 27396 -> clean 27347

{0: ['1426', '1427', '172'], 1: ['1066', '182', '222'], 2: ['229', '232', '244'], 3: ['1407', '1437', '180'], 4: ['12', '214', '231']}

           Car  Motorcycle  Bus  Truck  Tuktuk  Van  Pickup  Songthaew
val fold
0         1372         849   56    210      47   26      87        102
1         4068        1561   80    260      16   50     186         13
2         3279         992   55    242     120  148     127          2
3         3075         982   92    178      35   54      32          0
4         5940        2165  196    464      47   76      63          0

In [5]:
# write YOLO labels once (all train images), then per-fold image lists with repeat-factor sampling
YOLO_DIR = TMP / 'yolo'
if YOLO_DIR.exists():
    shutil.rmtree(YOLO_DIR)
(YOLO_DIR / 'images').mkdir(parents=True); (YOLO_DIR / 'labels').mkdir(parents=True)
by_img = dict(tuple(clean.groupby('image_id')))

def write(src, stem):
    shutil.copy(TRAIN_IMG_DIR / src, YOLO_DIR / 'images' / f'{stem}.jpg')
    g = by_img.get(src)
    lines = [] if g is None else [f'{r.class_id} {(r.x1 + r.x2) / 2 / W:.6f} {(r.y1 + r.y2) / 2 / H:.6f} {(r.x2 - r.x1) / W:.6f} {(r.y2 - r.y1) / H:.6f}'
                                  for r in g.itertuples()]
    (YOLO_DIR / 'labels' / f'{stem}.txt').write_text('\n'.join(lines))
    return str(YOLO_DIR / 'images' / f'{stem}.jpg')

f_c = clean.groupby('class_id').image_id.nunique() / len(train_files)
r_c = np.maximum(1, np.sqrt(0.15 / f_c)).clip(upper=4)
rs = np.random.default_rng(SEED)
base, reps = {}, {}
for f in train_files:
    base[f] = write(f, Path(f).stem)
    r = r_c[by_img[f].class_id.unique()].max() if f in by_img else 1
    n = int(math.floor(r) + (rs.random() < r - math.floor(r)))
    reps[f] = [write(f, f'{Path(f).stem}__rep{k}') for k in range(1, n)]

for k in range(N_FOLDS):
    tr = [p for f in train_files if fold_of_cam[cam_of(f)] != k for p in [base[f]] + reps[f]]
    va = [base[f] for f in train_files if fold_of_cam[cam_of(f)] == k]
    (YOLO_DIR / f'train_f{k}.txt').write_text('\n'.join(tr)); (YOLO_DIR / f'val_f{k}.txt').write_text('\n'.join(va))
    (YOLO_DIR / f'fold{k}.yaml').write_text(f"path: {YOLO_DIR}\ntrain: train_f{k}.txt\nval: val_f{k}.txt\nnc: 8\nnames: {CLASSES}\n")
    print(f'fold {k}: train {len(tr)} (incl. repeats)  val {len(va)}')

fold 0: train 2579 (incl. repeats)  val 605
fold 1: train 2639 (incl. repeats)  val 603
fold 2: train 2639 (incl. repeats)  val 580
fold 3: train 2664 (incl. repeats)  val 602
fold 4: train 2655 (incl. repeats)  val 601

## Metric (pycocotools, same as Kaggle) and prediction helpers

In [6]:
from pycocotools.coco import COCO
from pycocotools.cocoeval import COCOeval

def coco_map50(gt, pred, files):
    fid = {f: i for i, f in enumerate(files)}
    gt = gt[gt.image_id.isin(fid)]; pred = pred[pred.image_id.isin(fid)]
    ds = {'images': [{'id': i, 'file_name': f, 'width': W, 'height': H} for f, i in fid.items()],
          'categories': [{'id': k, 'name': n} for k, n in enumerate(CLASSES)],
          'annotations': [{'id': k + 1, 'image_id': fid[r.image_id], 'category_id': int(r.class_id),
                           'bbox': [float(r.x1), float(r.y1), float(r.x2 - r.x1), float(r.y2 - r.y1)],
                           'area': float((r.x2 - r.x1) * (r.y2 - r.y1)), 'iscrowd': 0} for k, r in enumerate(gt.itertuples())]}
    dets = [{'image_id': fid[r.image_id], 'category_id': int(r.class_id), 'score': float(r.confidence),
             'bbox': [float(r.x1), float(r.y1), float(r.x2 - r.x1), float(r.y2 - r.y1)]} for r in pred.itertuples()]
    with contextlib.redirect_stdout(io.StringIO()):
        cg = COCO(); cg.dataset = ds; cg.createIndex()
        E = COCOeval(cg, cg.loadRes(dets), 'bbox'); E.evaluate(); E.accumulate(); E.summarize()
    prec = E.eval['precision'][0, :, :, 0, 2]
    per = {CLASSES[k]: (round(float(prec[:, k][prec[:, k] > -1].mean()), 4) if (prec[:, k] > -1).any() else None) for k in range(8)}
    return round(float(E.stats[1]), 4), per

PRED_BATCH = int(os.environ.get('PRED_BATCH', 32))   # lower it on small GPUs

def predict(model, img_dir, files, batch=PRED_BATCH):
    rows = []
    for i in range(0, len(files), batch):
        chunk = [str(img_dir / f) for f in files[i:i + batch]]
        for p, r in zip(chunk, model.predict(chunk, imgsz=IMGSZ, conf=CONF, max_det=MAX_DET, augment=TTA, verbose=False, device=0)):
            b = r.boxes
            for (x1, y1, x2, y2), c, s in zip(b.xyxy.cpu().numpy(), b.cls.cpu().numpy(), b.conf.cpu().numpy()):
                rows.append((Path(p).name, int(c), float(s), float(x1), float(y1), float(x2), float(y2)))
    return pd.DataFrame(rows, columns=['image_id', 'class_id', 'confidence', 'x1', 'y1', 'x2', 'y2'])

## Train the folds of this session

In [7]:
fold_times = []
for k in FOLDS:
    fdir = OUT / f'fold{k}'
    if (fdir / 'test_pred.csv').exists():
        print(f'fold {k}: already done'); continue
    elapsed = (time.time() - T_START) / 3600
    if fold_times and elapsed + 1.15 * max(fold_times) > BUDGET_H:
        print(f'fold {k}: SKIPPED (elapsed {elapsed:.2f} h, last fold took {max(fold_times):.2f} h) -> run it in another session')
        continue
    t0 = time.time()
    run = TMP / 'runs' / f'fold{k}'
    if (fdir / 'best.pt').exists():            # weights already there (e.g. submitted weights) -> only predict
        print(f'fold {k}: using existing {fdir / "best.pt"}')
        train_this = False
    else:
        train_this = True
    args = dict(data=str(YOLO_DIR / f'fold{k}.yaml'), imgsz=IMGSZ, epochs=EPOCHS, patience=PATIENCE, seed=SEED,
                deterministic=True, cos_lr=True, close_mosaic=10, cache='ram', workers=4, plots=True,
                project=str(run.parent), name=run.name, exist_ok=True)
    if train_this:
        try:
            YOLO(MODEL).train(batch=BATCH_PER_GPU * max(N_GPU, 1), device=list(range(N_GPU)) if N_GPU > 1 else 0, **args)
        except Exception as e:                       # multi-GPU (DDP) failure -> fall back to one GPU
            print('multi-GPU training failed, retrying on 1 GPU:', repr(e)[:300])
            YOLO(MODEL).train(batch=BATCH_PER_GPU, device=0, **args)
        fdir.mkdir(parents=True, exist_ok=True)
        for fn in ['weights/best.pt', 'results.csv', 'args.yaml', 'confusion_matrix_normalized.png', 'results.png']:
            if (run / fn).exists():
                shutil.copy(run / fn, fdir / Path(fn).name)
    model = YOLO(str(fdir / 'best.pt'))
    val_files = [f for f in train_files if fold_of_cam[cam_of(f)] == k]
    vp = predict(model, TRAIN_IMG_DIR, val_files); vp.to_csv(fdir / 'val_pred.csv', index=False)
    m, per = coco_map50(train_df, vp, val_files)                  # raw labels, like Kaggle
    predict(model, TEST_IMG_DIR, test_files).to_csv(fdir / 'test_pred.csv', index=False)
    hours = (time.time() - t0) / 3600; fold_times.append(hours)
    meta = {'fold': k, 'val_cams': sorted(c for c, v in fold_of_cam.items() if v == k), 'val_map50': m, 'val_ap': per,
            'hours': round(hours, 2), 'model': MODEL, 'imgsz': IMGSZ, 'epochs': EPOCHS, 'tta': TTA, 'gpus': N_GPU}
    json.dump(meta, open(fdir / 'metrics.json', 'w'), indent=2)
    print(json.dumps(meta)); plog(json.dumps(meta))

fold 0: using existing cv_out\fold0\best.pt

{"fold": 0, "val_cams": ["1426", "1427", "172"], "val_map50": 0.4297, "val_ap": {"Car": 0.8744, "Motorcycle": 0.744, "Bus": 0.4267, "Truck": 0.4801, "Tuktuk": 0.5188, "Van": 0.1757, "Pickup": 0.2084, "Songthaew": 0.0092}, "hours": 0.05, "model": "yolo26m.pt", "imgsz": 960, "epochs": 30, "tta": true, "gpus": 1}
fold 1: using existing cv_out\fold1\best.pt

{"fold": 1, "val_cams": ["1066", "182", "222"], "val_map50": 0.52, "val_ap": {"Car": 0.8504, "Motorcycle": 0.7898, "Bus": 0.7184, "Truck": 0.5863, "Tuktuk": 0.4893, "Van": 0.4674, "Pickup": 0.2546, "Songthaew": 0.0036}, "hours": 0.05, "model": "yolo26m.pt", "imgsz": 960, "epochs": 30, "tta": true, "gpus": 1}
fold 2: using existing cv_out\fold2\best.pt

{"fold": 2, "val_cams": ["229", "232", "244"], "val_map50": 0.5024, "val_ap": {"Car": 0.8685, "Motorcycle": 0.7971, "Bus": 0.6131, "Truck": 0.5127, "Tuktuk": 0.4535, "Van": 0.3506, "Pickup": 0.4239, "Songthaew": 0.0}, "hours": 0.05, "model": "yolo26m.pt", "imgsz": 960, "epochs": 30, "tta": true, "gpus": 1}
fold 3: using existing cv_out\fold3\best.pt

{"fold": 3, "val_cams": ["1407", "1437", "180"], "val_map50": 0.7089, "val_ap": {"Car": 0.8947, "Motorcycle": 0.8483, "Bus": 0.7918, "Truck": 0.5605, "Tuktuk": 0.8357, "Van": 0.5005, "Pickup": 0.5311, "Songthaew": null}, "hours": 0.05, "model": "yolo26m.pt", "imgsz": 960, "epochs": 30, "tta": true, "gpus": 1}
fold 4: using existing cv_out\fold4\best.pt

{"fold": 4, "val_cams": ["12", "214", "231"], "val_map50": 0.5449, "val_ap": {"Car": 0.8638, "Motorcycle": 0.4989, "Bus": 0.6941, "Truck": 0.4526, "Tuktuk": 0.4762, "Van": 0.2903, "Pickup": 0.5384, "Songthaew": null}, "hours": 0.05, "model": "yolo26m.pt", "imgsz": 960, "epochs": 30, "tta": true, "gpus": 1}

## Out-of-fold CV score and WBF ensemble (uses every fold found in `cv_out/` and in attached inputs)

In [8]:
from ensemble_boxes import weighted_boxes_fusion
fold_dirs = {}
for d in sorted(glob.glob(str(OUT / 'fold*'))) + sorted(glob.glob('/kaggle/input/**/cv_out/fold*', recursive=True)):
    d = Path(d)
    if (d / 'test_pred.csv').exists():
        fold_dirs.setdefault(int(d.name[4:]), d)
print('folds available:', sorted(fold_dirs))
summary = [json.load(open(d / 'metrics.json')) for _, d in sorted(fold_dirs.items())]
display(pd.DataFrame(summary)[['fold', 'val_cams', 'val_map50', 'hours']])
if fold_dirs:
    oof = pd.concat([pd.read_csv(d / 'val_pred.csv') for d in fold_dirs.values()])
    oof_files = [f for f in train_files if fold_of_cam[cam_of(f)] in fold_dirs]
    cv, cv_ap = coco_map50(train_df, oof, oof_files)
    print(f'OUT-OF-FOLD CV mAP@50 over {len(oof_files)} images / folds {sorted(fold_dirs)}: {cv}')
    print(cv_ap)

folds available: [0, 1, 2, 3, 4]

   fold           val_cams  val_map50  hours
0     0  [1426, 1427, 172]     0.4297   0.05
1     1   [1066, 182, 222]     0.5200   0.05
2     2    [229, 232, 244]     0.5024   0.05
3     3  [1407, 1437, 180]     0.7089   0.05
4     4     [12, 214, 231]     0.5449   0.05

OUT-OF-FOLD CV mAP@50 over 2991 images / folds [0, 1, 2, 3, 4]: 0.4755
{'Car': 0.8657, 'Motorcycle': 0.6942, 'Bus': 0.6751, 'Truck': 0.4956, 'Tuktuk': 0.4828, 'Van': 0.3003, 'Pickup': 0.2899, 'Songthaew': 0.0006}

In [9]:
def wbf(preds, iou_thr=0.55, skip=CONF):
    by = [dict(tuple(p.groupby('image_id'))) for p in preds]
    rows = []
    for f in test_files:
        bl, sl, ll = [], [], []
        for d in by:
            g = d.get(f)
            if g is None:
                bl.append(np.zeros((0, 4))); sl.append(np.zeros(0)); ll.append(np.zeros(0)); continue
            bl.append(np.clip(g[['x1', 'y1', 'x2', 'y2']].values / [W, H, W, H], 0, 1)); sl.append(g.confidence.values); ll.append(g.class_id.values)
        if not any(len(s) for s in sl):
            continue
        b, s, l = weighted_boxes_fusion(bl, sl, ll, iou_thr=iou_thr, skip_box_thr=skip, conf_type='avg')
        for (x1, y1, x2, y2), sc, lb in zip(b * [W, H, W, H], s, l):
            rows.append((f, int(lb), float(sc), x1, y1, x2, y2))
    return pd.DataFrame(rows, columns=['image_id', 'class_id', 'confidence', 'x1', 'y1', 'x2', 'y2'])

if fold_dirs:
    ens = wbf([pd.read_csv(d / 'test_pred.csv') for _, d in sorted(fold_dirs.items())])
    ens = ens.round({'confidence': 5, 'x1': 2, 'y1': 2, 'x2': 2, 'y2': 2})
    ens = ens[(ens.x2 > ens.x1) & (ens.y2 > ens.y1)]
    ens = ens.sort_values(['image_id', 'confidence'], ascending=[True, False]).groupby('image_id').head(300).reset_index(drop=True)
    ens.insert(0, 'id', range(len(ens)))
    name = f"{Path(MODEL).stem}_{IMGSZ}_cv{len(fold_dirs)}fold_wbf.csv"
    ens.to_csv(OUT / name, index=False)
    print('saved', OUT / name, len(ens), 'rows,', ens.image_id.nunique(), 'images')
print(f'total time {(time.time() - T_START) / 3600:.2f} h')

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57573           0     0.59978           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5495           0     0.58152           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55377           0      0.5875           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50618           0     0.53644           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53325           0     0.59276           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50683           0     0.54565           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49429           0     0.52603           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52275           0     0.55515           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51667           0     0.54728           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49541           0     0.53085           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51161           0     0.54028           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.32609           0     0.38466           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58487           0     0.61539           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54605           0     0.58055           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46842           0     0.49316           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69823           0     0.73214           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63853           0     0.67539           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65353           0     0.67923           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54545           0     0.57896           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49172           0     0.51151           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.74912           1     0.80734           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60503           0     0.63408           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45763           0     0.50764           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44128           0     0.50508           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47088           0     0.51187           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61923           0     0.64899           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49891           0     0.52194           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62457           0     0.66378           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51061           0     0.53124           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63464           0     0.67672           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45449           0     0.48731           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.64867           0     0.68097           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54471           0     0.58731           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53165           0     0.58894           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5519           0     0.59501           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65831           0     0.69286           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55628           0     0.62407           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56985           0     0.61209           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54852           0     0.58402           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57236           0     0.60721           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5659           0     0.59689           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59194           0     0.62712           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57729           0     0.61585           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60152           0     0.62892           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61183           0      0.6328           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.40951           0     0.46782           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.39448           0     0.45535           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45458           0      0.5034           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55397           0     0.57966           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45922           0     0.48983           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63776           0     0.68101           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45691           0     0.49616           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44993           0     0.48516           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62735           0     0.66582           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68009           0     0.70519           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.43928           0     0.48034           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51958           0     0.55326           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55695           0     0.59521           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51375           0     0.54337           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63808           0     0.67674           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50139           0     0.52941           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49873           0     0.52305           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46518           0     0.50585           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.64538           0     0.69513           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62885           0     0.66715           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59644           0     0.63737           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56458           0     0.60725           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60058           0     0.65843           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49325           0     0.52982           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45657           0      0.5038           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59564           0     0.62736           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52224           0     0.54689           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66965           0     0.69937           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67009           0      0.6975           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65652           0     0.69081           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.64854           0     0.67965           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66275           0     0.70286           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54315           0     0.56894           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56007           0     0.58452           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52031           0     0.54646           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66774           0     0.70318           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66081           0     0.68858           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50207           0      0.5286           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53428           0     0.59687           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63104           0     0.66696           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52384           0     0.56264           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51069           0     0.53762           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55834           0     0.58984           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56258           0     0.59459           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.64681           0     0.67631           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5364           0     0.57206           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56536           0     0.60842           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52956           0     0.56091           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67119           0     0.72024           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53966           0     0.58939           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52395           0     0.55381           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5477           0     0.60175           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65562           0     0.69995           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.70552           0     0.75496           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51818           0     0.56735           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45437           0     0.50353           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53336           0     0.57974           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67862           0     0.73338           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58431           0     0.63409           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56883           0     0.63739           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69035           0      0.7435           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56497           0     0.60503           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55813           0     0.59835           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51177           0     0.54495           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56629           0     0.59351           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56862           0     0.60018           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54277           0     0.58463           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.72192           0     0.75762           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57167           0     0.62463           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.72903           0     0.76585           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50006           0     0.53904           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68712           0     0.71267           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45542           0     0.50363           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.41118           0      0.4692           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.42771           0      0.4792           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49589           0     0.53182           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46435           0     0.48217           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44931           0     0.47961           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.43848           0     0.47524           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.42976           0     0.46639           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47054           0     0.48798           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45875           0     0.48329           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61002           0     0.64064           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.73191           0     0.77655           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45983           0     0.48566           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45222           0     0.48388           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44669           0     0.47697           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.74743           0     0.77789           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.70807           0     0.73516           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56932           0     0.62055           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56984           0     0.60875           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56798           0     0.59715           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56911           0     0.59516           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.70438           0     0.72942           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69875           0     0.72289           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68884           0     0.72116           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54985           0     0.56803           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69043           0     0.72328           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68208           0     0.71719           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69303           0     0.71727           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54135           0     0.55946           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66486           0      0.7062           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67368           0     0.70049           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53706           0     0.56405           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55254           0     0.57233           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52223           0      0.5569           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51569           0     0.54145           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45337           0     0.47297           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67944           0     0.71387           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5927           0     0.62507           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57639           0     0.62003           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54856           0     0.59339           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56221           0     0.60186           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60675           0      0.6371           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55599           0     0.60854           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44115           0     0.47733           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.40916           0     0.47134           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.42707           0     0.47784           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63018           0     0.65675           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45072           0     0.48298           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53707           0     0.58013           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51686           0     0.55819           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58886           0     0.61787           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51902           0      0.5519           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4078           0     0.46033           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52481           0     0.55715           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50688           0     0.54984           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.70653           0     0.74534           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60538           0     0.64248           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61212           0     0.64886           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54802           0     0.57586           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52887           0     0.56016           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52132           0      0.5546           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5846           0     0.60977           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55399           0     0.59406           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.41232           0     0.46828           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52683           0     0.57344           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67501           0     0.69777           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57204           0     0.60882           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51764           0     0.56402           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68066           0     0.71233           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.42695           0     0.47721           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.43952           0     0.48187           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45684           0     0.50224           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50892           0     0.55666           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68965           0     0.72592           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.74742           0     0.83364           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4598           0     0.48313           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46108           0     0.48963           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63246           0     0.67036           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51366           0     0.54319           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62281           0      0.6581           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.41109           0     0.46646           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53578           0      0.5681           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51428           0     0.54187           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52146           0     0.56724           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57957           0     0.61292           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58646           0      0.6174           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67116           0     0.70763           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57673           0     0.60201           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50313           0     0.53371           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58877           0     0.62682           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67918           0     0.71659           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66144           0     0.70136           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57105           0     0.59802           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58016           0     0.61828           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.71845           0      0.7319           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5837           0     0.61085           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58081           0     0.61112           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61321           0     0.64675           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61124           0     0.63926           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60699           0     0.63235           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69275           0     0.71459           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67673           0     0.72216           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62679           0     0.67003           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58639           0     0.61662           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56601           0     0.59546           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56218           0     0.62597           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55559           0     0.58268           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57343           0     0.61143           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59034           0     0.61583           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67884           0     0.70807           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54274           0     0.57304           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5189           0     0.54503           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52232           0     0.55197           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53137           0     0.57899           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66874           0     0.70248           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67099           0     0.69384           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6468           0     0.67089           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58226           0     0.63237           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67192           0     0.71348           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.64172           0     0.66879           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50757           0     0.53884           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50332           0     0.53756           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45452           0     0.48165           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45072           0     0.47407           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.43173           0     0.47215           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46057           0     0.48803           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.97214           1           1           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.70321           0     0.74635           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60478           0     0.64927           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53829           0     0.59127           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58814           0     0.64688           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51221           0     0.56054           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55794           0      0.6143           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65355           0      0.6984           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56959           0     0.62514           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.71434           0     0.75233           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5276           0     0.57924           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6608           0     0.70722           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47539           0     0.53416           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.40661           0     0.47059           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66461           0     0.70388           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65312           0     0.69752           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61949           0     0.66676           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67074           0     0.71412           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46097           0     0.48673           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46283           0     0.50014           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45576           0     0.48202           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.64503           0     0.67287           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65315           0      0.6744           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63798           0     0.66676           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44601           0     0.48087           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66158           0     0.68538           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46937           0      0.5031           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5314           0     0.56088           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53856           0     0.56515           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47892           0     0.50735           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65806           0     0.68788           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48797           0     0.51428           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46071           0     0.49242           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59667           0     0.62318           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59018           0      0.6141           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6034           0       0.631           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69643           0     0.73786           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44992           0     0.48407           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.41234           0     0.43915           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69072           0     0.73032           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61181           0     0.63416           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.43672           0     0.47381           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45892           0     0.49767           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46154           0     0.50837           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49663           0     0.54456           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62756           0     0.65905           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48243           0     0.51843           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44153           0     0.49179           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59913           0     0.62627           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6036           0     0.63483           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45793           0     0.51913           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.40921           0     0.44919           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.39575           0     0.44346           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47857           0     0.53432           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6113           0      0.6423           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.41985           0     0.47855           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4109           0     0.46363           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58498           0     0.60971           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61682           0     0.65369           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63976           0     0.66951           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4593           0     0.50482           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.41269           0     0.45361           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61489           0     0.65754           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56751           0     0.61889           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.40949           0     0.47103           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.39307           0     0.44844           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48845           0     0.53931           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47503           0     0.53455           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5538           0     0.58893           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65959           0     0.69336           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57785           0     0.60214           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.70229           0     0.72773           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59174           0     0.62581           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55698           0     0.58304           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55197           0     0.57542           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54186           0     0.57343           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65142           0     0.68441           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45916           0     0.48853           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68422           0     0.70824           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55833           0     0.59185           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67631           0     0.71363           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51821           0     0.54903           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54983           0      0.5831           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52409           0     0.55216           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53628           0     0.56574           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51019           0     0.53513           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66613           0     0.69601           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51387           0      0.5377           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58589           0     0.61425           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53267           0     0.56356           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5279           0      0.5526           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51679           0     0.54147           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49822           0     0.52765           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50354           0     0.53076           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55042           0     0.58286           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5733           0      0.6031           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53459           0     0.56933           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5244           0     0.56547           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65425           0     0.68161           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53945           0     0.56287           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6769           0     0.70226           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49766           0     0.52389           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47331           0      0.5116           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56524           0     0.60268           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60901           0     0.63471           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59343           0     0.62464           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60309           0     0.62759           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59307           0     0.61501           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61198           0     0.64708           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.73119           0     0.78984           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51793           0     0.54192           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47188           0     0.49422           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51177           0     0.53512           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46106           0     0.48467           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44061           0     0.46455           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48197           0     0.50474           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50197           0     0.52499           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50755           0     0.53481           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50894           0     0.53027           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47253           0     0.50619           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          1     0.38873           1     0.62367].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49999           0     0.52382           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59614           0     0.63501           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5893           0     0.62742           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.74808           0     0.78854           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55511           0     0.58604           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.71524           0     0.74388           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6112           0     0.64468           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69979           0     0.74271           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59893           0     0.64875           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.42066           0     0.48436           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44014           0     0.49031           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60216           0     0.63585           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.40704           0     0.47358           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67052           0     0.70169           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6639           0      0.6908           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58602           0      0.6376           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4493           0     0.50084           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66607           0     0.71784           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68775           0     0.73232           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65428           0     0.70381           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.7142           0     0.75464           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59068           0     0.62463           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45882           0     0.50969           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.38946           0     0.46042           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68032           0     0.74295           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55442           0     0.60738           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56881           0     0.61889           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54106           0     0.59794           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5727           0     0.63024           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65574           0     0.67671           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47917           0     0.53244           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4686           0     0.52279           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63805           0      0.6953           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45948           0     0.50798           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55683           0     0.58312           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4479           0     0.50037           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52922           0     0.56584           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47572           0     0.51589           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67731           0     0.70406           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6818           0     0.70883           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4579           0     0.50386           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56024           0     0.59087           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56968           0     0.59676           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.72919           0     0.75602           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55243           0     0.58447           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44894           0     0.49464           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58944           0     0.61893           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54926           0     0.58336           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52652           0     0.55819           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53177           0     0.56433           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6809           0     0.71791           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61332           0     0.65086           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56128           0     0.60258           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50955           0     0.55421           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55087           0      0.5975           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5013           0     0.54007           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62009           0     0.64756           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54018           0     0.58588           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50002           0     0.53151           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.63605           0     0.67801           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67552           0     0.70406           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [      0.411           0     0.47177           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4595           0     0.48416           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44902           0     0.47863           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54499           0     0.58909           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55307           0     0.59754           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53435           0     0.58033           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45247           0     0.48285           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45879           0     0.49424           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61182           0     0.63126           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.43395           0      0.4766           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4885           0     0.53545           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49123           0      0.5159           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48342           0     0.50779           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54944           0     0.58352           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50079           0     0.52699           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58186           0     0.62411           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6756           0     0.70833           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67699           0     0.70916           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5006           0     0.52995           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66505           0     0.70339           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6831           0     0.71545           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57126           0     0.59566           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56379           0     0.58989           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67105           0     0.70477           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67578           0     0.70543           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58649           0     0.64025           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68051           0     0.71529           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59362           0     0.62657           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [      0.592           0     0.61625           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58989           0     0.62411           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5248           0     0.55378           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53243           0     0.55576           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.73158           0     0.78802           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.73554           0     0.80787           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49009           0     0.51805           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48143           0     0.50849           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47233           0      0.4977           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5235           0     0.54788           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54896           0     0.57525           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.73094           0     0.77792           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49904           0     0.53143           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.73806           0     0.78898           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65451           0     0.68771           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55751           0     0.58373           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59002           0      0.6193           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.70236           0     0.74442           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.41404           0     0.46704           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51121           0     0.54334           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62316           0     0.65478           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60007           0     0.63047           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46334           0     0.49355           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69812           0     0.73366           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58535           0     0.61932           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44797           0     0.47713           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.74672           0     0.83396           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45827           0     0.50194           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52656           0     0.58306           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45234           0     0.48401           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51979           0     0.56057           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65997           0     0.70327           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.70346           0     0.74578           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67066           0     0.69912           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66607           0     0.69887           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65896           0       0.695           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67293           0      0.7042           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46589           0     0.49633           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47626           0     0.50702           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57175           0     0.61326           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [      0.591           0     0.64073           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55193           0     0.61123           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53429           0     0.59733           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62621           0     0.66306           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51759           0     0.54501           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6797           0     0.72727           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52381           0     0.55578           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57689           0      0.6321           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59195           0     0.62901           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60537           0     0.63995           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56486           0     0.62313           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61726           0       0.666           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44978           0     0.48913           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52789           0     0.56717           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65425           0     0.68504           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.75592           0     0.78914           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62995           0     0.67744           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4553           0     0.50143           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66616           0     0.72351           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.74678           0     0.77621           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53169           0     0.57975           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65829           0     0.71121           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.74438           0      0.7869           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49453           0     0.54252           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45918           0     0.48467           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5116           0     0.54403           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51789           0     0.54926           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45336           0     0.48175           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5034           0     0.52928           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56927           0     0.61029           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50888           0     0.53379           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50046           0     0.52425           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5187           0     0.54414           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66247           0     0.69988           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69376           0     0.72077           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.69715           0     0.72849           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52131           0     0.55932           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57689           0     0.60159           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56699           0     0.59063           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66787           0     0.69652           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51538           0     0.54093           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58804           0     0.64833           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60534           0     0.66869           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52283           0     0.54746           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68131           0     0.70993           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.65983           0     0.67813           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55482           0     0.58529           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5591           0     0.59311           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55021           0     0.57642           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.73083           0     0.79015           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66974           0     0.69257           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67047           0     0.70519           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.62431           0     0.66472           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57243           0      0.5912           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58342           0     0.60737           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45914           0      0.4836           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67348           0     0.70762           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51522           0     0.54313           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54403           0     0.57289           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54478           0     0.58421           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47913           0     0.51767           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44194           0     0.48863           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46303           0     0.51444           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.43061           0     0.48363           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.74194           0     0.77903           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59996           0     0.63555           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53386           0      0.5727           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58461           0     0.62662           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4837           0     0.52844           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60517           0     0.65164           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55694           0     0.58256           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.55924           0     0.59026           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.60593           0     0.62991           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61058           0     0.63664           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.61013           0     0.64427           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48289           0     0.51911           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57698           0       0.617           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56607           0     0.60331           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.6035           0     0.62114           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58802           0     0.62068           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47623           0     0.51663           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50059           0     0.54296           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46611           0     0.50801           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48734           0     0.52746           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53514           0     0.56574           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49125           0     0.53803           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.54016           0     0.56982           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.56918           0      0.5925           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52893           0     0.55518           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45295           0     0.50497           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.40971           0     0.46702           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.64514           0     0.67499           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46732           0     0.50444           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47679           0     0.50857           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48667           0     0.51799           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49118           0     0.53583           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47837           0     0.53478           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46292           0     0.51074           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47133           0     0.50859           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4582           0     0.51065           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49631           0     0.54902           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59169           0     0.62538           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.41158           0     0.45033           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.48573           0      0.5269           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.66542           0      0.6997           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.64005           0     0.66492           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.3946           0     0.44827           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45774           0     0.49313           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59476           0     0.63977           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.57599           0     0.62089           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44404           0     0.49552           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.67156           0     0.72082           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44334           0     0.49968           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46641           0     0.53003           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49941           0     0.55798           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.68858           0     0.74405           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47848           0     0.54152           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.59377           0     0.64489           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.51246           0      0.5641           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.42198           0     0.49037           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.58762           0     0.62909           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.40326           0      0.4749           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45925           0     0.49404           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.46308           0     0.50574           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45046           0      0.4881           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.5177           0     0.53871           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.4371           0     0.47971           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.50487           0     0.53681           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52053           0     0.54563           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.49197           0     0.53157           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.42729           0     0.46007           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.44581           0     0.48015           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.42104           0      0.4509           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.47512           0     0.52556           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.53669           0     0.58407           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.41097           0     0.44136           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.45437           0     0.48173           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.93915           1     0.98932           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [ 0.00021387           0    0.054584           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.96325           1     0.99979           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [ 0.00043355           0    0.051746           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.95091           1     0.99934           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.95756           1           1           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94819           1     0.99885           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.95367           1     0.99874           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.95048           1     0.99936           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94597           1     0.99931           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.9434           1     0.99974           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94944           1     0.99849           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.95439           1     0.99853           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.97375           1     0.99994           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94206           1     0.99976           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94138           1           1           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.96499           1     0.99965           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94045           1     0.99897           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.9656           1     0.99956           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.93932           1     0.99933           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.96034           1      0.9996           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.93708           1     0.99993           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94097           1     0.99976           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94945           1     0.99964           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94219           1     0.99927           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.98798           1           1           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0           0     0.05137           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0           0    0.051567           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.039676           1    0.061786           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.032536           1    0.060855           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.042835           1     0.07054           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.051123           1    0.097728           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.044894           1    0.086562           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.073456           1     0.11458           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.067102           1     0.10747           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0           0    0.050814           0].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          1     0.87402           1           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0           1    0.061325           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.066813           1     0.10343           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.055352           1     0.10096           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0           1    0.060036           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.012487           1    0.090508           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.020102           1    0.060916           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.061211           1      0.1011           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.066706           1     0.10294           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0           1     0.10106           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.063991           1    0.093455           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.069156           1     0.11734           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0           1    0.033703           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          1     0.80673           1           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.044112           1    0.085477           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0           1    0.070874           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.033088           1    0.064242           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.074872           1     0.11371           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.097074           1     0.12654           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.07276           1     0.12007           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.028875           1     0.06299           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.04475           1    0.076372           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0           1    0.031535           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.083711           1     0.12735           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.085336           1     0.10916           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.095367           1      0.1202           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.10427           1     0.12988           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.080353           1     0.10243           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.86697           1           1           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.018869           1    0.050828           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.023852           1    0.080585           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.065729           1     0.10494           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          1     0.86284           1           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.071536           1     0.11181           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.065366           1     0.10522           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.059758           1    0.098248           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.037088           1    0.076279           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.026594           1     0.06606           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.056057           1     0.10544           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.049584           1    0.095409           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.014911           1    0.062225           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.027765           1    0.063147           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.045393           1    0.077271           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.075078           1     0.11393           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.064915           1    0.099566           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.070609           1     0.10754           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.055564           1    0.090248           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.019778           1     0.05215           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.071078           1     0.11264           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.075393           1     0.11288           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.014703           1    0.049607           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.069834           1     0.10094           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [   0.015505           1    0.091977           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52279           1     0.55023           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.52115           1     0.55834           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.31932           1     0.36857           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0      0.7176           0     0.78815].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0     0.71283           0     0.77477].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.95738           1     0.99985           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0     0.76275           0     0.84641].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [          0     0.67547           0     0.73761].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [       0.97           1     0.99997           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [     0.9799           1     0.99923           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.95507           1     0.99984           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))
C:\Users\User\anaconda3\envs\dsde\Lib\site-packages\ensemble_boxes\ensemble_boxes_wbf.py:66: UserWarning: Zero area box skipped: [    0.94746           1           1           1].
  warnings.warn("Zero area box skipped: {}.".format(box_part))

saved cv_out\yolo26m_960_cv5fold_wbf.csv 109650 rows, 1013 images
total time 0.27 h